# Generated by Django 5.0.1 on 2024-03-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaevaluacionclinica',
            name='imagen',
            field=models.ImageField(default=1, upload_to='imagenes/'),
            preserve_default=False,
        ),
    ]
