# Generated by Django 4.2.5 on 2024-05-22 15:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluaciónPsicologicaNiños',
            fields=[
                ('idEvaluacionPsicologica', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('nota_evolucion', models.TextField()),
                ('proxima_cita', models.DateField()),
                ('CURP', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_pacientes.paciente')),
                ('numero_expediente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_pacientes.fichapsicologicaniño')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluaciónPsicologicaAdultos',
            fields=[
                ('idEvaluacionPsicologica', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('nota_evolucion', models.TextField()),
                ('proxima_cita', models.DateField()),
                ('CURP', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_pacientes.paciente')),
                ('numero_expediente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion_pacientes.fichapsicologicaadulto')),
            ],
        ),
    ]
