# Generated by Django 5.0.1 on 2024-03-25 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0002_hojaevaluacionclinica_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojaevaluacionclinica',
            name='imagen',
        ),
    ]
