# Generated by Django 5.0.1 on 2024-02-13 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0002_alter_historianutricion_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
