# Generated by Django 4.2.5 on 2024-05-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0002_evaluaciónpsicologicaniños_and_more'),
        ('gestion_pacientes', '0003_remove_hojaevaluacionclinica_imagen'),
    ]

    operations = [
    ]
