# Generated by Django 5.0.1 on 2024-05-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0003_remove_hojaevaluacionclinica_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaevaluacionclinica',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
