# Generated by Django 5.0.1 on 2024-05-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0004_hojaevaluacionclinica_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojaevaluacionclinica',
            name='imagen',
        ),
    ]
