# Generated by Django 4.2.5 on 2024-06-28 19:16

from django.db import migrations, models
import gestion_pacientes.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0004_merge_20240524_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='historianutricion',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=gestion_pacientes.models.ruta_documentNutricion),
        ),
    ]
