# Generated by Django 5.0.1 on 2024-06-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0005_remove_hojaevaluacionclinica_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='hojaevaluacionclinica',
            name='archivo',
            field=models.FileField(default=1, upload_to='documentos/'),
            preserve_default=False,
        ),
    ]
