# Generated by Django 5.0.1 on 2024-06-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0006_hojaevaluacionclinica_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojaevaluacionclinica',
            name='archivo',
        ),
    ]
