# Generated by Django 4.2.5 on 2024-06-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0005_historianutricion_archivo'),
        ('gestion_pacientes', '0008_hojaevaluacionclinica_archivo'),
    ]

    operations = [
    ]
