# Generated by Django 5.0.1 on 2024-06-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0004_merge_20240524_1145'),
        ('gestion_pacientes', '0008_hojaevaluacionclinica_archivo'),
    ]

    operations = [
    ]
