# Generated by Django 4.2.5 on 2024-07-01 19:35

from django.db import migrations, models
import gestion_pacientes.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0009_merge_20240630_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='examenmedico',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=gestion_pacientes.models.ruta_examen_medico),
        ),
        migrations.AddField(
            model_name='fichapsicologicaadulto',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=gestion_pacientes.models.ruta_fichapsico_adulto),
        ),
        migrations.AddField(
            model_name='fichapsicologicaniño',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=gestion_pacientes.models.ruta_fichapsico_nino),
        ),
        migrations.AlterField(
            model_name='hojaevaluacionclinica',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=gestion_pacientes.models.ruta_hoja_clinica),
        ),
    ]
