# Generated by Django 5.0.1 on 2024-07-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0009_merge_20240625_1311'),
        ('gestion_pacientes', '0010_examenmedico_archivo_fichapsicologicaadulto_archivo_and_more'),
    ]

    operations = [
    ]
